CLASS yrdcl_local_event_consumption DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR EVENTS OF YRDR_OrderTP_000.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS yrdcl_local_event_consumption IMPLEMENTATION.
ENDCLASS.
